name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - hydra-core=1.3.3
  - matplotlib=3.9.1
  - pandas=2.2.0
  - jupyterlab=4.1.0
  - pip=24.0
  - pip:
      - mlflow==2.9.0
      - wandb==0.16.3