name: nyc_airbnb_dev
channels:
  - defaults
dependencies:
  - pip=20.3.3
  - pip:
      - wandb==0.10.31
      - mlflow==1.30.1
      - ipython==7.21.0
      - notebook==6.2.0
      - jupyterlab==3.0.10
      - cookiecutter==1.7.2
      - hydra-core==1.0.6
      - matplotlib==3.3.4
      - pandas==1.2.3
      - git==2.41.0
